### PR TITLE
Eslint and stylelint on CI

### LINKED ISSUE #52: Linters on CI

### PR DESCRIPTION
**Pull request by prekel**
closes #52

### CODE REVIEW

**Comment by prekel** [comment]
(I will squash this pr before merge)

**Review by moetazaneta — COMMENTED** [review]
I think we should test code **only** before commit, so testing on CI is unnecessary (repetition).

**Comment by prekel** [comment]
> I think we should test code **only** before commit, so testing on CI is unnecessary (repetition).

I think linting must be part of code review.

**Review by NightOfNights — APPROVED** [review]

**Comment by NightOfNights** [comment]
> I think we should test code **only** before commit, so testing on CI is unnecessary (repetition).

Let's stick to CI linting for awhile. If we come to a good and working solution for linting before commits, then let's change auto linting to it.

**Review by Moltenship — APPROVED** [review]

**Pull request merged**
